version: "3"
services:
  flask:
    build: .
    image: count-app:${TAG}
    container_name: hit-app-${TAG}
    ports:
      - 5000:5000
    volumes:
      - main:/home/countdb/${TAG}:rw
    environment:
      - FLASK_ENV=${ENV}
    networks:
      - main
      
    # depends_on:
    #   - db
  # db:
  #   image: "redis:alpine"
  #   container_name: hit-count-db
  #   volumes:
  #     - app-vol:/home/appdb:rw

volumes:
  main:
    external: true
networks:
  main:
    external: true
